version: '2.3'
services:
  test-cpu-base:
    build:
      context: .
      dockerfile: Dockerfile.test.cpu
      args:
        UBUNTU_VERSION: 20.04
        GPP_VERSION: 7
        MPI_KIND: None
        PYTHON_VERSION: 3.9
        TENSORFLOW_PACKAGE: tensorflow-cpu==2.14.0
        KERAS_PACKAGE: keras==2.14.0
        PYTORCH_PACKAGE: torch==2.1.2+cpu
        PYTORCH_LIGHTNING_PACKAGE: pytorch-lightning==1.5.9
        TORCHVISION_PACKAGE: torchvision==0.16.2+cpu
        MXNET_PACKAGE: mxnet==1.9.1
        PYSPARK_PACKAGE: pyspark==3.4.0
        SPARK_PACKAGE: spark-3.4.0/spark-3.4.0-bin-hadoop3.tgz
        HOROVOD_BUILD_FLAGS: HOROVOD_WITH_GLOO=1
    privileged: true
    shm_size: 8gb

  # our baseline first
  test-cpu-gloo-py3_9-tf2_14_0-keras2_14_0-torch2_1_2-mxnet1_9_1-pyspark3_4_0:
    extends: test-cpu-base

  # permute MPI kinds
  test-cpu-mpich-py3_9-tf2_14_0-keras2_14_0-torch2_1_2-mxnet1_9_1-pyspark3_4_0:
    extends: test-cpu-base
    build:
      args:
        MPI_KIND: MPICH
        HOROVOD_BUILD_FLAGS: HOROVOD_WITHOUT_GLOO=1

  test-cpu-oneccl-py3_9-tf2_14_0-keras2_14_0-torch2_1_2-mxnet1_9_1-pyspark3_4_0:
    extends: test-cpu-base
    build:
      args:
        MPI_KIND: ONECCL
        HOROVOD_BUILD_FLAGS: HOROVOD_WITHOUT_GLOO=1

  test-cpu-openmpi-py3_9-tf2_14_0-keras2_14_0-torch2_1_2-mxnet1_9_1-pyspark3_4_0:
    extends: test-cpu-base
    build:
      args:
        MPI_KIND: OpenMPI
        HOROVOD_BUILD_FLAGS: HOROVOD_WITHOUT_GLOO=1

  test-cpu-openmpi-gloo-py3_9-tf2_14_0-keras2_14_0-torch2_1_2-mxnet1_9_1-pyspark3_4_0:
    extends: test-cpu-base
    build:
      args:
        MPI_KIND: OpenMPI

  test-cpu-gloo-py3_9-tf2_12_1-keras2_12_0-torch1_13_1-mxnet1_7_0_p2-pyspark3_4_0:
    extends: test-cpu-base
    build:
      args:
        TENSORFLOW_PACKAGE: tensorflow-cpu==2.12.1
        KERAS_PACKAGE: keras==2.12.0
        PYTORCH_PACKAGE: torch==1.13.1+cpu
        TORCHVISION_PACKAGE: torchvision==0.14.1+cpu
        MXNET_PACKAGE: mxnet==1.7.0.post2

  # then our baseline again, omitted ...
  test-cpu-openmpi-gloo-py3_9-tfhead-keras_none-torchhead-mxnethead-pyspark3_4_0:
    extends: test-cpu-base
    build:
      args:
        MPI_KIND: OpenMPI
        TENSORFLOW_PACKAGE: tf-nightly
        KERAS_PACKAGE: None
        PYTORCH_PACKAGE: torch-nightly
        TORCHVISION_PACKAGE: torchvision
        PYTORCH_LIGHTNING_PACKAGE: pytorch-lightning==1.5.9
        MXNET_PACKAGE: mxnet-nightly

  test-gpu-base:
    build:
      context: .
      dockerfile: Dockerfile.test.gpu
      args:
        GPP_VERSION: 7
        MPI_KIND: None
        PYTHON_VERSION: 3.9
        PYSPARK_PACKAGE: pyspark==3.4.0
        SPARK_PACKAGE: spark-3.4.0/spark-3.4.0-bin-hadoop3.tgz
        HOROVOD_BUILD_FLAGS: HOROVOD_GPU_OPERATIONS=NCCL
        HOROVOD_MIXED_INSTALL: 0
    runtime: nvidia
    # We plumb CUDA_VISIBLE_DEVICES instead of NVIDIA_VISIBLE_DEVICES because
    # the latter does not work in privileged mode that we use in the containers.
    environment:
      - CUDA_VISIBLE_DEVICES
    privileged: true
    shm_size: 8gb


  # The container isn't provided for CUDA 10 anymore. The lowest version of mxnet available for cu112 is 1.8.0.post0.
  test-gpu-gloo-py3_9-tf2_12_1-keras2_12_0-torch1_13_1-mxnet1_8_0_p0-pyspark3_4_0:
    extends: test-gpu-base
    build:
      args:
        CUDA_DOCKER_VERSION: 11.6.2-devel-ubuntu20.04
        CUDNN_VERSION: 8.4.1.50-1+cuda11.6
        NCCL_VERSION_OVERRIDE: 2.11.4-1+cuda11.6
        TENSORFLOW_PACKAGE: tensorflow==2.12.1
        KERAS_PACKAGE: keras==2.12.0
        PYTORCH_PACKAGE: torch==1.13.1+cu116
        PYTORCH_LIGHTNING_PACKAGE: pytorch-lightning==1.5.9
        TORCHVISION_PACKAGE: torchvision==0.14.1+cu116
        MXNET_PACKAGE: mxnet-cu112==1.8.0.post0

  test-gpu-gloo-py3_9-tf2_13_0-keras2_13_1-torch2_0_1-mxnet1_8_0_p0-pyspark3_4_0:
    extends: test-gpu-base
    build:
      args:
        CUDA_DOCKER_VERSION: 11.6.2-devel-ubuntu20.04
        CUDNN_VERSION: 8.4.1.50-1+cuda11.6
        NCCL_VERSION_OVERRIDE: 2.11.4-1+cuda11.6
        # tensorflow package supports GPU from 2.11.1 and 2.12.0 on
        TENSORFLOW_PACKAGE: tensorflow==2.13.0
        KERAS_PACKAGE: keras==2.13.1
        PYTORCH_PACKAGE: torch==2.0.1+cu118
        PYTORCH_LIGHTNING_PACKAGE: pytorch-lightning==1.5.9
        TORCHVISION_PACKAGE: torchvision==0.15.2+cu118
        MXNET_PACKAGE: mxnet-cu112==1.8.0.post0

  test-gpu-openmpi-gloo-py3_9-tf2_14_0-keras2_14_0-torch2_1_2-mxnet1_9_1-pyspark3_4_0:
    extends: test-gpu-base
    build:
      args:
        CUDA_DOCKER_VERSION: 11.8.0-devel-ubuntu20.04
        CUDNN_VERSION: 8.6.0.163-1+cuda11.8
        NCCL_VERSION_OVERRIDE: 2.16.5-1+cuda11.8
        MPI_KIND: OpenMPI
        # tensorflow package supports GPU from 2.11.1 and 2.12.0 on
        TENSORFLOW_PACKAGE: tensorflow==2.14.0
        KERAS_PACKAGE: keras==2.14.0
        PYTORCH_PACKAGE: torch==2.1.2+cu118
        PYTORCH_LIGHTNING_PACKAGE: pytorch-lightning==1.5.9
        TORCHVISION_PACKAGE: torchvision==0.16.2+cu118
        MXNET_PACKAGE: mxnet-cu112==1.9.1

  test-gpu-openmpi-gloo-py3_9-tfhead-keras_none-torchhead-mxnethead-pyspark3_4_0:
    extends: test-gpu-base
    build:
      args:
        CUDA_DOCKER_VERSION: 11.8.0-devel-ubuntu20.04
        CUDNN_VERSION: 8.6.0.163-1+cuda11.8
        NCCL_VERSION_OVERRIDE: 2.16.5-1+cuda11.8
        MPI_KIND: OpenMPI
        TENSORFLOW_PACKAGE: tf-nightly
        KERAS_PACKAGE: None
        PYTORCH_PACKAGE: torch-nightly-cu118
        PYTORCH_LIGHTNING_PACKAGE: pytorch-lightning==1.5.9
        TORCHVISION_PACKAGE: torchvision
        MXNET_PACKAGE: mxnet-nightly-cu112

  test-mixed-openmpi-gloo-py3_9-tf2_14_0-keras2_14_0-torch2_1_2-mxnet1_9_1-pyspark3_4_0:
    extends: test-gpu-base
    build:
      args:
        CUDA_DOCKER_VERSION: 11.8.0-devel-ubuntu20.04
        CUDNN_VERSION: 8.6.0.163-1+cuda11.8
        NCCL_VERSION_OVERRIDE: 2.16.5-1+cuda11.8
        MPI_KIND: OpenMPI
        # tensorflow package supports GPU from 2.11.1 and 2.12.0 on
        TENSORFLOW_PACKAGE: tensorflow==2.14.0
        KERAS_PACKAGE: keras==2.14.0
        PYTORCH_PACKAGE: torch==2.1.2+cu118
        PYTORCH_LIGHTNING_PACKAGE: pytorch-lightning==1.5.9
        TORCHVISION_PACKAGE: torchvision==0.16.2+cu118
        MXNET_PACKAGE: mxnet-cu112==1.9.1
        HOROVOD_BUILD_FLAGS: ""
        HOROVOD_MIXED_INSTALL: 1
